/** Sent to MCP clients on connect (soft guidance; not a hard sandbox). */
export const SERVER_INSTRUCTIONS = [
  "hitl-gate-mcp: Human-in-the-Loop approval gate for side-effectful Agent actions.",
  "",
  "MUST call assess_and_gate BEFORE any irreversible/side-effect work, including:",
  "delete/overwrite files, .env/secrets, git force-push/reset --hard, DROP/TRUNCATE,",
  "prod deploy, curl|bash, chmod 777, npm/pypi publish, mass email/payment.",
  "When unsure whether an action is dangerous, still call assess_and_gate (or list_dangerous_ops).",
  "",
  "Pass code_context (active file, paths, short summary) and optional planned_changes.files.",
  "ONLY high/critical risks set gate_required=true and open the IDE approval form.",
  "Proceed ONLY when ticket.status is approved / can_execute=true.",
  "If rejected, cancelled, expired, or still pending: STOP. Do not execute.",
  "Chat replies like「可以」are NOT approval; only the form/ticket status counts.",
  "",
  "After approved execution: call submit_execution_report with actual_files and verify_runs;",
  "show comparison summary_zh to the user.",
  "",
  "When the user asks for 审批记录 / approval history / audit: call list_approval_history",
  "and present summary_zh (markdown table) in chat. Do not invent records.",
  "",
  "Hard client hooks (Rule/Skill) are optional: run `npx hitl-gate-mcp init` in the project",
  "after configuring this MCP in the IDE. Soft instructions alone are not 100% reliable.",
].join("\n");
